### ISSUE TITLE
Fatal error while importing a `bunnynet_pullzone` resource

### ISSUE THREAD

**Issue by adriantombu** [BunnyWay/terraform-provider-bunnynet#20]
I'm in the process of importing my existing Bunny infrastructure on Terraform and when I try to import a `bunnynet_pullzone` resource I get a fatal error. I didn't have any problem while importing `dns_zone` and `dns_record` records.

## Minimal code to reproduce

```terraform
import {
  to = bunnynet_pullzone.xxx
  id = "resource_id"
}

resource "bunnynet_pullzone" "xxx" {
  name = "pullzone_name"
}
```

## Output

```
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵

Stack trace from the terraform-provider-bunnynet_v0.5.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x100f0e8ac]

goroutine 50 [running]:
github.com/bunnyway/terraform-provider-bunnynet/internal/pullzoneresourcevalidator.middlewareScriptValidator.ValidateResource({}, {0x1014fc5c8, 0x14000129290}, {{{{0x1015014a8, 0x14000129830}, {0x1013ea540, 0x14000515110}}, {0x1015035a8, 0x14000398f00}}}, 0x14000138018)
	github.com/bunnyway/terraform-provider-bunnynet/internal/pullzoneresourcevalidator/middleware_script.go:36 +0x1cc
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ValidateResourceConfig(0x140000e1688, {0x1014fc5c8, 0x14000129290}, 0x1400039d6e0, 0x140004835e8)
	github.com/hashicorp/terraform-plugin-framework@v1.13.0/internal/fwserver/server_validateresourceconfig.go:72 +0x474
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ValidateResourceConfig(0x140000e1688, {0x1014fc5c8?, 0x140001291a0?}, 0x140001381c8)
	github.com/hashicorp/terraform-plugin-framework@v1.13.0/internal/proto6server/server_validateresourceconfig.go:47 +0x368
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ValidateResourceConfig(0x140001f4fa0, {0x1014fc5c8?, 0x14000128a50?}, 0x14000130200)
	github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov6/tf6server/server.go:724 +0x25c
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ValidateResourceConfig_Handler({0x1014d2e40, 0x140001f4fa0}, {0x1014fc5c8, 0x14000128a50}, 0x1400012c280, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:503 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000182e00, {0x1014fc5c8, 0x140001289c0}, {0x101502340, 0x140003f6000}, 0x1400015a480, 0x140002ea360, 0x101a2bc88, 0x0)
	google.golang.org/grpc@v1.67.1/server.go:1394 +0xb78
google.golang.org/grpc.(*Server).handleStream(0x14000182e00, {0x101502340, 0x140003f6000}, 0x1400015a480)
	google.golang.org/grpc@v1.67.1/server.go:1805 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.67.1/server.go:1029 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 20
	google.golang.org/grpc@v1.67.1/server.go:1040 +0x13c

Error: The terraform-provider-bunnynet_v0.5.0 plugin crashed!
```

**Comment by rafael-at-bunny** [comment]
Hi!

Thank you for your report.

This happens because your pullzone declaration is missing the `routing` and `origin` blocks. Try with this:

```terraform
import {
  to = bunnynet_pullzone.xxx
  id = "resource_id"
}

resource "bunnynet_pullzone" "xxx" {
  name = "pullzone_name"

  origin {
    type = "OriginUrl"
    url  = "https://bunny.net"
  }

  routing {
    tier = "Standard"
  }
}
```

In any case, I'll release a fix later this week so Terraform will show the correct error instead of a panic.

Thank you.
